server:
  port: ${PORT:5000}
token:
  exp:
    minutos: 60
  signing:
    key: ${TOKEN_KEY}
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
springdoc:
  swagger-ui:
    path: /
cloudinary:
  config:
    api:
      name: ${CLOUDINARY_NAME}
      key: ${CLOUDINARY_KEY}
      secret: ${CLOUDINARY_SECRET}
brevio:
  openapi:
    dev-url: http://localhost:5000/
    prod-url: https://####.######.com/